name: Build App and Push gh-pages Branch

on:
  push:
    branches:
      - master

jobs:
  create_build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      VITE_APP_EMAIL_ACCOUNT_ID: ${{ secrets.REACT_APP_EMAIL_ACCOUNT_ID }}
      VITE_APP_EMAIL_SERVICE_ID: ${{ secrets.REACT_APP_EMAIL_SERVICE_ID }}
      VITE_APP_EMAIL_TEMPLATE_ID: ${{ secrets.REACT_APP_EMAIL_TEMPLATE_ID }}

    strategy:
      matrix:
        node-version: [lts/fermium]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: create build
        run: npm run build

      - name: Push created build
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
